### ISSUE TITLE
Multiple Account Credentials

### ISSUE THREAD

**Issue by swager-steven** [Uptycs/cloudquery#83]
Was wondering if there is a way to configure access to multiple accounts without using access keys (for AWS)?

Attempted to create a read-only role in multiple accounts and then grant the instance running the cloudquery extension the ability to assume those other roles, however it doesnt appear to be able to assume the roles configured and only accesses its current account.

- Read-only role configured in every account and has the cloudquery account as a trusted entity to assume the role.
- IAM EC2 role assigned to instance allows instance to assume role from other account and read-only access to current account
- credentials file setup as:
```
[profile default]
role_arn = arn:aws:iam::xxxxxxxxxxxxxx:role/cloudquery
credential_source = Ec2InstanceMetadata

[profile other_account]
role_arn = arn:aws:iam::yyyyyyyyyyyyy:role/cloudquery
source_profile = default
```

**Comment by apatil-uptycs** [comment]
Hi @swager-steven , it is possible to configure access to multiple accounts using RoleARN+ExternalId. Setup will be as follows:
- Cloudquery account : Account used by cloudquery. Credentials for this account should be in .credentials file.
- Tenant accounts : These are accounts which you want to monitor. All these accounts should have a role configured with trust relationship with cloudquery account. Role should have required permissions for cloudquery to query the data. The roleARN + ExternalId configuration should go to cloudquery extension_config.json.

**Comment by swager-steven** [comment]
Hello Amol,
Appreciate the response.  Your response did work, however had a quick follow up.  It appears that if we have multiple accounts in the file it runs through the accounts one by one (is that a correct observation?), wonder if there is a way to run a query against multiple accounts at once?  Or is that the reason for suggesting one instance per account?

Thanks!

**Comment by apatil-uptycs** [comment]
@swager-steven I'm glad I could help. Right now we run all accounts one by one but it still supports multiple accounts, and you can query all account using cloudquery. We can very well change the implementation to go through all accounts at once by using go routines. We have followed serial approach to limit number of simultaneous connections and API calls.
One instance per account is suggested for the use cases where you want to use instance profile for authentication. Did I answer all your questions ?

Thanks,
..... Amol
